# Generated by Django 4.2.16 on 2026-03-10 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("category", "0002_alter_transaction_payment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "next_due_date",
                    models.DateField(help_text="The next date this EMI is due"),
                ),
                (
                    "reminder_time",
                    models.TimeField(help_text="Time of day to send the reminder"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_processed_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date the EMI expense was added",
                        null=True,
                    ),
                ),
                (
                    "last_notified_date",
                    models.DateField(
                        blank=True, help_text="Last date a reminder was sent", null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="category.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
