# Generated by Django 4.2.16 on 2026-03-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_emi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emi",
            name="next_due_date",
        ),
        migrations.AddField(
            model_name="emi",
            name="due_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The day of the month the EMI is due (1-31)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emi",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="The date the EMI ends", null=True
            ),
        ),
        migrations.AddField(
            model_name="emi",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="The date the EMI starts", null=True
            ),
        ),
    ]
