# Generated by Django 4.2.16 on 2026-06-14 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0004_remove_emi_next_due_date_emi_due_day_emi_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emi",
            name="due_day",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="The day of the month the EMI is due (1-31)"
            ),
        ),
        migrations.AlterField(
            model_name="emi",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="The date the EMI ends"
            ),
        ),
        migrations.AlterField(
            model_name="emi",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="The date the EMI starts"
            ),
        ),
    ]
