# Generated by Django 4.2.16 on 2026-02-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jwt_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
