# Generated by Django 4.2.26 on 2025-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempUserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp_hash", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
