# Generated by Django 4.2.26 on 2026-01-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_managers_user_device_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="app_version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
