# Generated by Django 4.2.26 on 2026-01-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_app_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
