# Generated by Django 4.2.16 on 2026-02-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
        ("group", "0002_grouptransaction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptransaction",
            name="to_person",
            field=models.ForeignKey(
                blank=True,
                help_text="The person receiving the payment (for income/settlement type).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_transactions",
                to="group.person",
            ),
        ),
        migrations.AlterField(
            model_name="grouptransaction",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_transactions",
                to="category.category",
            ),
            preserve_default=False,
        ),
    ]
