# Generated by Django 4.2.16 on 2026-02-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
        ("group", "0003_grouptransaction_to_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouptransaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_transactions",
                to="category.category",
            ),
        ),
    ]
