# Generated by Django 4.2.16 on 2026-02-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0004_alter_grouptransaction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouptransaction",
            name="payment_type",
            field=models.CharField(default="cash", max_length=50),
        ),
    ]
