# Generated by Django 4.2.16 on 2026-03-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0005_alter_grouptransaction_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptransaction",
            name="include_owner",
            field=models.BooleanField(
                default=True,
                help_text="Whether the group owner is included in the split.",
            ),
        ),
        migrations.AddField(
            model_name="grouptransaction",
            name="split_between",
            field=models.ManyToManyField(
                blank=True,
                help_text="The people among whom the expense is split. If empty and include_owner is True, split with everyone.",
                related_name="involved_in_transactions",
                to="group.person",
            ),
        ),
    ]
