# Generated by Django 4.2.16 on 2026-03-07 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0006_grouptransaction_include_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouptransaction",
            name="include_owner",
        ),
        migrations.RemoveField(
            model_name="grouptransaction",
            name="split_between",
        ),
    ]
