# Generated by Django 4.2.16 on 2026-06-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
        ("group", "0008_grouptransaction_include_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptransaction",
            name="goal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_transactions",
                to="goals.goalentry",
            ),
        ),
    ]
